-- MySQL Script generated by MySQL Workbench
-- Tue Feb 14 09:22:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FullStackDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FullStackDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FullStackDB` DEFAULT CHARACTER SET utf8 ;
USE `FullStackDB` ;

-- -----------------------------------------------------
-- Table `FullStackDB`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FullStackDB`.`Student` (
  `idStudentnr` INT NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idStudentnr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FullStackDB`.`Opleiding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FullStackDB`.`Opleiding` (
  `idOpleidingscode` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `niveau` VARCHAR(45) NULL,
  PRIMARY KEY (`idOpleidingscode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FullStackDB`.`Student opleiding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FullStackDB`.`Student opleiding` (
  `idStudent opleiding` INT NOT NULL,
  `startdatum` DATE NULL,
  `einddatum` DATE NULL,
  `diploma` VARCHAR(45) NULL,
  `idStudentnr` VARCHAR(45) NOT NULL,
  `idOpleidingscode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStudent opleiding`, `idStudentnr`, `idOpleidingscode`),
  INDEX `fk_Student opleiding_Student_idx` (`idStudentnr` ASC) VISIBLE,
  INDEX `fk_Student opleiding_Opleiding1_idx` (`idOpleidingscode` ASC) VISIBLE,
  CONSTRAINT `fk_Student opleiding_Student`
    FOREIGN KEY (`idStudentnr`)
    REFERENCES `FullStackDB`.`Student` (`idStudentnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student opleiding_Opleiding1`
    FOREIGN KEY (`idOpleidingscode`)
    REFERENCES `FullStackDB`.`Opleiding` (`idOpleidingscode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
